<?php
/**
 * Created by PhpStorm.
 * User: yangyang
 * Date: 2018/11/26
 * Time: 下午2:34
 */

namespace app\http\controller;

use classes\IndexClass;

class IndexController extends FirstController
{
    private $class;
    protected $url = 'index';
    protected $set = [];

    public function __construct()
    {
        $this->class = new IndexClass();//初始化操作类

        $this->set = $this->class->set();//获取网站设置

        if ($this->set['webSwitch'] == 'off') exit($this->set['webCloseReason']);//网站关闭
    }

    /**
     * 视图
     *
     * @param string $view
     * @param array $data
     * @return \think\response\View
     */
    protected function view($view = '', $data = [])
    {
        $data['member'] = $this->class->member();//会员信息
        $data['set'] = $this->set;//设定数组
        $data['errors'] = null;
        $data['success'] = null;

        //获取提示
        $errors = session('errors');
        $success = session('success');

        //初始化errors视图变量
        if (!is_null($errors) && is_string($errors)) $data['errors'] = $errors;

        //初始化success视图变量
        if (!is_null($success) && is_string($success)) $data['success'] = $success;

        //删除提示
        session('errors', null);
        session('success', null);

        return parent::view($view, $data); // TODO: Change the autogenerated stub
    }

    /**
     * ajax成功
     *
     * @param string $url
     * @param string $success
     * @param array $other
     * @return \think\response\Json
     */
    protected function success($url = '', $success = '操作成功', $other = [])
    {
        $result = [
            'status' => 'success',
            'url' => $url,
            'message' => $success,
        ];

        return json(array_merge($result, $other));
    }
}